# Generated by Django 3.0.7 on 2020-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='details',
            field=models.TextField(default='Null', max_length=999),
            preserve_default=False,
        ),
    ]
