# Generated by Django 3.0.7 on 2020-07-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200729_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobAs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Job'),
        ),
    ]
