# Generated by Django 3.0.7 on 2020-07-31 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobAs',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Job'),
        ),
    ]
