# Generated by Django 3.0.7 on 2020-07-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200731_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='doneby',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
