# Generated by Django 3.0.7 on 2020-08-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_job_asto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_logout',
            field=models.DateField(blank=True, default='1970-01-01', null=True),
        ),
    ]
