# Generated by Django 3.0.7 on 2020-08-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
