# Generated by Django 3.0.7 on 2020-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_job_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staff_requested',
            field=models.BooleanField(default=False),
        ),
    ]
