# Generated by Django 3.0.7 on 2020-07-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('totalcases', models.CharField(max_length=100)),
                ('newcases', models.CharField(max_length=100)),
                ('totaldeathes', models.CharField(max_length=100)),
                ('newdeathes', models.CharField(max_length=100)),
                ('totalrecovered', models.CharField(max_length=100)),
                ('activecases', models.CharField(max_length=100)),
                ('criticalcases', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
