# Generated by Django 3.0.7 on 2020-07-07 21:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corona',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
