# Generated by Django 3.0.7 on 2020-07-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_countrylist'),
        ('covid19', '0003_auto_20200709_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corona',
            name='countrypick',
        ),
        migrations.AlterField(
            model_name='corona',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.countryList'),
        ),
    ]
