# Generated by Django 3.0.7 on 2020-07-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0004_auto_20200710_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corona',
            old_name='country',
            new_name='name',
        ),
    ]
