# Generated by Django 3.0.7 on 2020-07-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0005_auto_20200710_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corona',
            name='name',
        ),
        migrations.AddField(
            model_name='corona',
            name='country',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
