# Generated by Django 3.0.7 on 2020-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0006_auto_20200710_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='worldCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
    ]
