# Generated by Django 3.0.7 on 2020-07-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0007_worldcountries'),
    ]

    operations = [
        migrations.CreateModel(
            name='arabicCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
                ('call', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='worldcountries',
            name='arname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worldcountries',
            name='call',
            field=models.CharField(default='null', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldcountries',
            name='duname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worldcountries',
            name='esname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worldcountries',
            name='frname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worldcountries',
            name='grname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
