# Generated by Django 3.0.7 on 2020-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0008_auto_20200712_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldcountries',
            old_name='duname',
            new_name='dename',
        ),
        migrations.AddField(
            model_name='arabiccountries',
            name='dename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='arabiccountries',
            name='esname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='arabiccountries',
            name='frname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='arabiccountries',
            name='grname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='arabiccountries',
            name='runame',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worldcountries',
            name='runame',
            field=models.CharField(default='', max_length=100),
        ),
    ]
