# Generated by Django 3.0.7 on 2020-07-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0009_auto_20200712_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldcountries',
            name='call',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
