# Generated by Django 3.0.7 on 2020-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='techNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('img', models.URLField()),
                ('href', models.CharField(max_length=999)),
                ('content', models.TextField()),
            ],
        ),
    ]
